import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import { createInlineScript } from "create-script/react";
var _this = this;
var InlineScript = createInlineScript("/*\n * ATTENTION: An \"eval-source-map\" devtool has been used.\n * This devtool is neither made for production nor for readable output files.\n * It uses \"eval()\" calls to create a separate source file with attached SourceMaps in the browser devtools.\n * If you are trying to read the output file, select a different devtool (https://webpack.js.org/configuration/devtool/)\n * or disable the default devtool with \"devtool: false\".\n * If you are looking for production-ready output files, see mode: \"production\" (https://webpack.js.org/configuration/mode/).\n */\n/******/ (function() { // webpackBootstrap\n/******/ \t\"use strict\";\n/******/ \tvar __webpack_modules__ = ({\n\n/***/ \"./inline.ts\":\n/*!*******************!*\\\n  !*** ./inline.ts ***!\n  \\*******************/\n/***/ (function(module, __webpack_exports__, __webpack_require__) {\n\neval(\"__webpack_require__.r(__webpack_exports__);\\n/* module decorator */ module = __webpack_require__.hmd(module);\\nconsole.log(\\\"hello world\\\");\\n/* harmony default export */ __webpack_exports__[\\\"default\\\"] = (null);\\nvar _a, _b;\\n// Legacy CSS implementations will `eval` browser code in a Node.js context\\n// to extract CSS. For backwards compatibility, we need to check we're in a\\n// browser context before continuing.\\nif (typeof self !== 'undefined' && // AMP / No-JS mode does not inject these helpers:\\n'$RefreshHelpers;
console.log("InlineScript", InlineScript);
var Home = function() {
    return(/*#__PURE__*/ _jsxs("div", {
        className: styles.container,
        __source: {
            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
            lineNumber: 12,
            columnNumber: 5
        },
        __self: _this,
        children: [
            /*#__PURE__*/ _jsxs(Head, {
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 13,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsx("title", {
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 14,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: "Create Next App"
                    }),
                    /*#__PURE__*/ _jsx("meta", {
                        name: "description",
                        content: "Generated by create next app",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 15,
                            columnNumber: 9
                        },
                        __self: _this
                    }),
                    /*#__PURE__*/ _jsx("link", {
                        rel: "icon",
                        href: "/favicon.ico",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 16,
                            columnNumber: 9
                        },
                        __self: _this
                    })
                ]
            }),
            /*#__PURE__*/ _jsxs("main", {
                className: styles.main,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 19,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsxs("h1", {
                        className: styles.title,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 20,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Welcome to ",
                            /*#__PURE__*/ _jsx("a", {
                                href: "https://nextjs.org",
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 21,
                                    columnNumber: 22
                                },
                                __self: _this,
                                children: "Next.js!"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("p", {
                        className: styles.description,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 24,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Get started by editing ",
                            /*#__PURE__*/ _jsx("code", {
                                className: styles.code,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 25,
                                    columnNumber: 34
                                },
                                __self: _this,
                                children: "pages/index.tsx"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                        className: styles.grid,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 28,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/docs",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 29,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 30,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Documentation →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 31,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Find in-depth information about Next.js features and API."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/learn",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 34,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 35,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 36,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn about Next.js in an interactive course with quizzes!"
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://github.com/vercel/next.js/tree/master/examples",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 39,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 40,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Examples →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 41,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Discover and deploy boilerplate example Next.js projects."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 44,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 48,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Deploy →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 49,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Instantly deploy your Next.js site to a public URL with Vercel."
                                    })
                                ]
                            })
                        ]
                    })
                ]
            }),
            /*#__PURE__*/ _jsx("footer", {
                className: styles.footer,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 54,
                    columnNumber: 7
                },
                __self: _this,
                children: /*#__PURE__*/ _jsxs("a", {
                    href: "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                    target: "_blank",
                    rel: "noopener noreferrer",
                    __source: {
                        fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                        lineNumber: 55,
                        columnNumber: 9
                    },
                    __self: _this,
                    children: [
                        "Powered by",
                        " ",
                        /*#__PURE__*/ _jsx("span", {
                            className: styles.logo,
                            __source: {
                                fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                lineNumber: 61,
                                columnNumber: 11
                            },
                            __self: _this,
                            children: /*#__PURE__*/ _jsx(Image, {
                                src: "/vercel.svg",
                                alt: "Vercel Logo",
                                width: 72,
                                height: 16,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 62,
                                    columnNumber: 13
                                },
                                __self: _this
                            })
                        })
                    ]
                })
            })
        ]
    }));
};
_c = Home;
export default Home;
var _c;
$RefreshReg$(_c, "Home");


;
    var _a, _b;
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' &&
        // AMP / No-JS mode does not inject these helpers:
        '$RefreshHelpers$' in self) {
        var currentExports = module.__proto__.exports;
        var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;
        // This cannot happen in MainTemplate because the exports mismatch between
        // templating and execution.
        self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);
        // A module can be accepted automatically based on its exports, e.g. when
        // it is a Refresh Boundary.
        if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {
            // Save the previous exports on update so we can compare the boundary
            // signatures.
            module.hot.dispose(function (data) {
                data.prevExports = currentExports;
            });
            // Unconditionally accept an update to this module, we'll check if it's
            // still a Refresh Boundary later.
            module.hot.accept();
            // This field is set when the previous version of this module was a
            // Refresh Boundary, letting us know we need to check for invalidation or
            // enqueue an update.
            if (prevExports !== null) {
                // A boundary can become ineligible if its exports are incompatible
                // with the previous exports.
                //
                // For example, if you add/remove/change exports, we'll want to
                // re-execute the importing modules, and force those components to
                // re-render. Similarly, if you convert a class component to a
                // function, we want to invalidate the boundary.
                if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {
                    module.hot.invalidate();
                }
                else {
                    self.$RefreshHelpers$.scheduleUpdate();
                }
            }
        }
        else {
            // Since we just executed the code for the module, it's possible that the
            // new exports made it ineligible for being a boundary.
            // We only care about the case when we were _previously_ a boundary,
            // because we already accepted this update (accidental side effect).
            var isNoLongerABoundary = prevExports !== null;
            if (isNoLongerABoundary) {
                module.hot.invalidate();
            }
        }
    }
 in self) {\\n    var currentExports = module.__proto__.exports;\\n    var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;\\n    // This cannot happen in MainTemplate because the exports mismatch between\\n    // templating and execution.\\n    self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);\\n    // A module can be accepted automatically based on its exports, e.g. when\\n    // it is a Refresh Boundary.\\n    if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {\\n        // Save the previous exports on update so we can compare the boundary\\n        // signatures.\\n        module.hot.dispose(function(data) {\\n            data.prevExports = currentExports;\\n        });\\n        // Unconditionally accept an update to this module, we'll check if it's\\n        // still a Refresh Boundary later.\\n        module.hot.accept();\\n        // This field is set when the previous version of this module was a\\n        // Refresh Boundary, letting us know we need to check for invalidation or\\n        // enqueue an update.\\n        if (prevExports !== null) {\\n            // A boundary can become ineligible if its exports are incompatible\\n            // with the previous exports.\\n            //\\n            // For example, if you add/remove/change exports, we'll want to\\n            // re-execute the importing modules, and force those components to\\n            // re-render. Similarly, if you convert a class component to a\\n            // function, we want to invalidate the boundary.\\n            if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {\\n                module.hot.invalidate();\\n            } else {\\n                self.$RefreshHelpers$.scheduleUpdate();\\n            }\\n        }\\n    } else {\\n        // Since we just executed the code for the module, it's possible that the\\n        // new exports made it ineligible for being a boundary.\\n        // We only care about the case when we were _previously_ a boundary,\\n        // because we already accepted this update (accidental side effect).\\n        var isNoLongerABoundary = prevExports !== null;\\n        if (isNoLongerABoundary) {\\n            module.hot.invalidate();\\n        }\\n    }\\n}\\n\\n\\n;\\n    var _a, _b;\\n    // Legacy CSS implementations will `eval` browser code in a Node.js context\\n    // to extract CSS. For backwards compatibility, we need to check we're in a\\n    // browser context before continuing.\\n    if (typeof self !== 'undefined' &&\\n        // AMP / No-JS mode does not inject these helpers:\\n        '$RefreshHelpers;
console.log("InlineScript", InlineScript);
var Home = function() {
    return(/*#__PURE__*/ _jsxs("div", {
        className: styles.container,
        __source: {
            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
            lineNumber: 12,
            columnNumber: 5
        },
        __self: _this,
        children: [
            /*#__PURE__*/ _jsxs(Head, {
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 13,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsx("title", {
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 14,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: "Create Next App"
                    }),
                    /*#__PURE__*/ _jsx("meta", {
                        name: "description",
                        content: "Generated by create next app",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 15,
                            columnNumber: 9
                        },
                        __self: _this
                    }),
                    /*#__PURE__*/ _jsx("link", {
                        rel: "icon",
                        href: "/favicon.ico",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 16,
                            columnNumber: 9
                        },
                        __self: _this
                    })
                ]
            }),
            /*#__PURE__*/ _jsxs("main", {
                className: styles.main,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 19,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsxs("h1", {
                        className: styles.title,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 20,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Welcome to ",
                            /*#__PURE__*/ _jsx("a", {
                                href: "https://nextjs.org",
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 21,
                                    columnNumber: 22
                                },
                                __self: _this,
                                children: "Next.js!"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("p", {
                        className: styles.description,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 24,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Get started by editing ",
                            /*#__PURE__*/ _jsx("code", {
                                className: styles.code,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 25,
                                    columnNumber: 34
                                },
                                __self: _this,
                                children: "pages/index.tsx"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                        className: styles.grid,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 28,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/docs",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 29,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 30,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Documentation →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 31,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Find in-depth information about Next.js features and API."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/learn",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 34,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 35,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 36,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn about Next.js in an interactive course with quizzes!"
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://github.com/vercel/next.js/tree/master/examples",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 39,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 40,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Examples →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 41,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Discover and deploy boilerplate example Next.js projects."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 44,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 48,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Deploy →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 49,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Instantly deploy your Next.js site to a public URL with Vercel."
                                    })
                                ]
                            })
                        ]
                    })
                ]
            }),
            /*#__PURE__*/ _jsx("footer", {
                className: styles.footer,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 54,
                    columnNumber: 7
                },
                __self: _this,
                children: /*#__PURE__*/ _jsxs("a", {
                    href: "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                    target: "_blank",
                    rel: "noopener noreferrer",
                    __source: {
                        fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                        lineNumber: 55,
                        columnNumber: 9
                    },
                    __self: _this,
                    children: [
                        "Powered by",
                        " ",
                        /*#__PURE__*/ _jsx("span", {
                            className: styles.logo,
                            __source: {
                                fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                lineNumber: 61,
                                columnNumber: 11
                            },
                            __self: _this,
                            children: /*#__PURE__*/ _jsx(Image, {
                                src: "/vercel.svg",
                                alt: "Vercel Logo",
                                width: 72,
                                height: 16,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 62,
                                    columnNumber: 13
                                },
                                __self: _this
                            })
                        })
                    ]
                })
            })
        ]
    }));
};
_c = Home;
export default Home;
var _c;
$RefreshReg$(_c, "Home");


;
    var _a, _b;
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' &&
        // AMP / No-JS mode does not inject these helpers:
        '$RefreshHelpers$' in self) {
        var currentExports = module.__proto__.exports;
        var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;
        // This cannot happen in MainTemplate because the exports mismatch between
        // templating and execution.
        self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);
        // A module can be accepted automatically based on its exports, e.g. when
        // it is a Refresh Boundary.
        if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {
            // Save the previous exports on update so we can compare the boundary
            // signatures.
            module.hot.dispose(function (data) {
                data.prevExports = currentExports;
            });
            // Unconditionally accept an update to this module, we'll check if it's
            // still a Refresh Boundary later.
            module.hot.accept();
            // This field is set when the previous version of this module was a
            // Refresh Boundary, letting us know we need to check for invalidation or
            // enqueue an update.
            if (prevExports !== null) {
                // A boundary can become ineligible if its exports are incompatible
                // with the previous exports.
                //
                // For example, if you add/remove/change exports, we'll want to
                // re-execute the importing modules, and force those components to
                // re-render. Similarly, if you convert a class component to a
                // function, we want to invalidate the boundary.
                if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {
                    module.hot.invalidate();
                }
                else {
                    self.$RefreshHelpers$.scheduleUpdate();
                }
            }
        }
        else {
            // Since we just executed the code for the module, it's possible that the
            // new exports made it ineligible for being a boundary.
            // We only care about the case when we were _previously_ a boundary,
            // because we already accepted this update (accidental side effect).
            var isNoLongerABoundary = prevExports !== null;
            if (isNoLongerABoundary) {
                module.hot.invalidate();
            }
        }
    }
 in self) {\\n        var currentExports = module.__proto__.exports;\\n        var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;\\n        // This cannot happen in MainTemplate because the exports mismatch between\\n        // templating and execution.\\n        self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);\\n        // A module can be accepted automatically based on its exports, e.g. when\\n        // it is a Refresh Boundary.\\n        if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {\\n            // Save the previous exports on update so we can compare the boundary\\n            // signatures.\\n            module.hot.dispose(function (data) {\\n                data.prevExports = currentExports;\\n            });\\n            // Unconditionally accept an update to this module, we'll check if it's\\n            // still a Refresh Boundary later.\\n            module.hot.accept();\\n            // This field is set when the previous version of this module was a\\n            // Refresh Boundary, letting us know we need to check for invalidation or\\n            // enqueue an update.\\n            if (prevExports !== null) {\\n                // A boundary can become ineligible if its exports are incompatible\\n                // with the previous exports.\\n                //\\n                // For example, if you add/remove/change exports, we'll want to\\n                // re-execute the importing modules, and force those components to\\n                // re-render. Similarly, if you convert a class component to a\\n                // function, we want to invalidate the boundary.\\n                if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {\\n                    module.hot.invalidate();\\n                }\\n                else {\\n                    self.$RefreshHelpers$.scheduleUpdate();\\n                }\\n            }\\n        }\\n        else {\\n            // Since we just executed the code for the module, it's possible that the\\n            // new exports made it ineligible for being a boundary.\\n            // We only care about the case when we were _previously_ a boundary,\\n            // because we already accepted this update (accidental side effect).\\n            var isNoLongerABoundary = prevExports !== null;\\n            if (isNoLongerABoundary) {\\n                module.hot.invalidate();\\n            }\\n        }\\n    }\\n//# sourceURL=[module]\\n//# sourceMappingURL=data:application/json;charset=utf-8;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoiLi9pbmxpbmUudHMuanMiLCJtYXBwaW5ncyI6Ijs7QUFFQUEsT0FBTSxDQUFBQyxHQUFBLEVBQWE7QUFBQTtBQUFBLElBQUFDLEVBQUEsRUFBQUMsRUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBLFdBQUFDLElBQUE7QUFBQSxzQkFBQUEsSUFBQTtJQUFBLElBQUFDLGNBQUEsR0FBQUMsTUFBQSxDQUFBQyxTQUFBLENBQUFDLE9BQUE7SUFBQSxJQUFBQyxXQUFBLElBQUFOLEVBQUEsSUFBQUQsRUFBQSxHQUFBSSxNQUFBLENBQUFJLEdBQUEsQ0FBQUMsSUFBQSxjQUFBVCxFQUFBLHVCQUFBQSxFQUFBLENBQUFPLFdBQUEsY0FBQU4sRUFBQSxjQUFBQSxFQUFBO0lBQUE7SUFBQTtJQUFBQyxJQUFBLENBQUFRLGdCQUFBLENBQUFDLDhCQUFBLENBQUFSLGNBQUEsRUFBQUMsTUFBQSxDQUFBUSxFQUFBO0lBQUE7SUFBQTtJQUFBLElBQUFWLElBQUEsQ0FBQVEsZ0JBQUEsQ0FBQUcsc0JBQUEsQ0FBQVYsY0FBQTtRQUFBO1FBQUE7UUFBQUMsTUFBQSxDQUFBSSxHQUFBLENBQUFNLE9BQUEsVUFBQUwsSUFBQTtZQUFBQSxJQUFBLENBQUFGLFdBQUEsR0FBQUosY0FBQTtRQUFBO1FBQUE7UUFBQTtRQUFBQyxNQUFBLENBQUFJLEdBQUEsQ0FBQU8sTUFBQTtRQUFBO1FBQUE7UUFBQTtRQUFBLElBQUFSLFdBQUE7WUFBQTtZQUFBO1lBQUE7WUFBQTtZQUFBO1lBQUE7WUFBQTtZQUFBLElBQUFMLElBQUEsQ0FBQVEsZ0JBQUEsQ0FBQU0sb0NBQUEsQ0FBQVQsV0FBQSxFQUFBSixjQUFBO2dCQUFBQyxNQUFBLENBQUFJLEdBQUEsQ0FBQVMsVUFBQTtZQUFBO2dCQUFBZixJQUFBLENBQUFRLGdCQUFBLENBQUFRLGNBQUE7WUFBQTtRQUFBO0lBQUE7UUFBQTtRQUFBO1FBQUE7UUFBQTtRQUFBLElBQUFDLG1CQUFBLEdBQUFaLFdBQUE7UUFBQSxJQUFBWSxtQkFBQTtZQUFBZixNQUFBLENBQUFJLEdBQUEsQ0FBQVMsVUFBQTtRQUFBO0lBQUE7QUFBQSIsInNvdXJjZXMiOlsid2VicGFjazovL19OX0UvLi9pbmxpbmUudHM/ZTE0NCJdLCJzb3VyY2VzQ29udGVudCI6WyJjb25zb2xlLmxvZyhcImhlbGxvIHdvcmxkXCIpO1xuZXhwb3J0IGRlZmF1bHQgbnVsbDtcblxuXG47XG4gICAgdmFyIF9hLCBfYjtcbiAgICAvLyBMZWdhY3kgQ1NTIGltcGxlbWVudGF0aW9ucyB3aWxsIGBldmFsYCBicm93c2VyIGNvZGUgaW4gYSBOb2RlLmpzIGNvbnRleHRcbiAgICAvLyB0byBleHRyYWN0IENTUy4gRm9yIGJhY2t3YXJkcyBjb21wYXRpYmlsaXR5LCB3ZSBuZWVkIHRvIGNoZWNrIHdlJ3JlIGluIGFcbiAgICAvLyBicm93c2VyIGNvbnRleHQgYmVmb3JlIGNvbnRpbnVpbmcuXG4gICAgaWYgKHR5cGVvZiBzZWxmICE9PSAndW5kZWZpbmVkJyAmJlxuICAgICAgICAvLyBBTVAgLyBOby1KUyBtb2RlIGRvZXMgbm90IGluamVjdCB0aGVzZSBoZWxwZXJzOlxuICAgICAgICAnJFJlZnJlc2hIZWxwZXJzJCcgaW4gc2VsZikge1xuICAgICAgICB2YXIgY3VycmVudEV4cG9ydHMgPSBtb2R1bGUuX19wcm90b19fLmV4cG9ydHM7XG4gICAgICAgIHZhciBwcmV2RXhwb3J0cyA9IChfYiA9IChfYSA9IG1vZHVsZS5ob3QuZGF0YSkgPT09IG51bGwgfHwgX2EgPT09IHZvaWQgMCA/IHZvaWQgMCA6IF9hLnByZXZFeHBvcnRzKSAhPT0gbnVsbCAmJiBfYiAhPT0gdm9pZCAwID8gX2IgOiBudWxsO1xuICAgICAgICAvLyBUaGlzIGNhbm5vdCBoYXBwZW4gaW4gTWFpblRlbXBsYXRlIGJlY2F1c2UgdGhlIGV4cG9ydHMgbWlzbWF0Y2ggYmV0d2VlblxuICAgICAgICAvLyB0ZW1wbGF0aW5nIGFuZCBleGVjdXRpb24uXG4gICAgICAgIHNlbGYuJFJlZnJlc2hIZWxwZXJzJC5yZWdpc3RlckV4cG9ydHNGb3JSZWFjdFJlZnJlc2goY3VycmVudEV4cG9ydHMsIG1vZHVsZS5pZCk7XG4gICAgICAgIC8vIEEgbW9kdWxlIGNhbiBiZSBhY2NlcHRlZCBhdXRvbWF0aWNhbGx5IGJhc2VkIG9uIGl0cyBleHBvcnRzLCBlLmcuIHdoZW5cbiAgICAgICAgLy8gaXQgaXMgYSBSZWZyZXNoIEJvdW5kYXJ5LlxuICAgICAgICBpZiAoc2VsZi4kUmVmcmVzaEhlbHBlcnMkLmlzUmVhY3RSZWZyZXNoQm91bmRhcnkoY3VycmVudEV4cG9ydHMpKSB7XG4gICAgICAgICAgICAvLyBTYXZlIHRoZSBwcmV2aW91cyBleHBvcnRzIG9uIHVwZGF0ZSBzbyB3ZSBjYW4gY29tcGFyZSB0aGUgYm91bmRhcnlcbiAgICAgICAgICAgIC8vIHNpZ25hdHVyZXMuXG4gICAgICAgICAgICBtb2R1bGUuaG90LmRpc3Bvc2UoZnVuY3Rpb24gKGRhdGEpIHtcbiAgICAgICAgICAgICAgICBkYXRhLnByZXZFeHBvcnRzID0gY3VycmVudEV4cG9ydHM7XG4gICAgICAgICAgICB9KTtcbiAgICAgICAgICAgIC8vIFVuY29uZGl0aW9uYWxseSBhY2NlcHQgYW4gdXBkYXRlIHRvIHRoaXMgbW9kdWxlLCB3ZSdsbCBjaGVjayBpZiBpdCdzXG4gICAgICAgICAgICAvLyBzdGlsbCBhIFJlZnJlc2ggQm91bmRhcnkgbGF0ZXIuXG4gICAgICAgICAgICBtb2R1bGUuaG90LmFjY2VwdCgpO1xuICAgICAgICAgICAgLy8gVGhpcyBmaWVsZCBpcyBzZXQgd2hlbiB0aGUgcHJldmlvdXMgdmVyc2lvbiBvZiB0aGlzIG1vZHVsZSB3YXMgYVxuICAgICAgICAgICAgLy8gUmVmcmVzaCBCb3VuZGFyeSwgbGV0dGluZyB1cyBrbm93IHdlIG5lZWQgdG8gY2hlY2sgZm9yIGludmFsaWRhdGlvbiBvclxuICAgICAgICAgICAgLy8gZW5xdWV1ZSBhbiB1cGRhdGUuXG4gICAgICAgICAgICBpZiAocHJldkV4cG9ydHMgIT09IG51bGwpIHtcbiAgICAgICAgICAgICAgICAvLyBBIGJvdW5kYXJ5IGNhbiBiZWNvbWUgaW5lbGlnaWJsZSBpZiBpdHMgZXhwb3J0cyBhcmUgaW5jb21wYXRpYmxlXG4gICAgICAgICAgICAgICAgLy8gd2l0aCB0aGUgcHJldmlvdXMgZXhwb3J0cy5cbiAgICAgICAgICAgICAgICAvL1xuICAgICAgICAgICAgICAgIC8vIEZvciBleGFtcGxlLCBpZiB5b3UgYWRkL3JlbW92ZS9jaGFuZ2UgZXhwb3J0cywgd2UnbGwgd2FudCB0b1xuICAgICAgICAgICAgICAgIC8vIHJlLWV4ZWN1dGUgdGhlIGltcG9ydGluZyBtb2R1bGVzLCBhbmQgZm9yY2UgdGhvc2UgY29tcG9uZW50cyB0b1xuICAgICAgICAgICAgICAgIC8vIHJlLXJlbmRlci4gU2ltaWxhcmx5LCBpZiB5b3UgY29udmVydCBhIGNsYXNzIGNvbXBvbmVudCB0byBhXG4gICAgICAgICAgICAgICAgLy8gZnVuY3Rpb24sIHdlIHdhbnQgdG8gaW52YWxpZGF0ZSB0aGUgYm91bmRhcnkuXG4gICAgICAgICAgICAgICAgaWYgKHNlbGYuJFJlZnJlc2hIZWxwZXJzJC5zaG91bGRJbnZhbGlkYXRlUmVhY3RSZWZyZXNoQm91bmRhcnkocHJldkV4cG9ydHMsIGN1cnJlbnRFeHBvcnRzKSkge1xuICAgICAgICAgICAgICAgICAgICBtb2R1bGUuaG90LmludmFsaWRhdGUoKTtcbiAgICAgICAgICAgICAgICB9XG4gICAgICAgICAgICAgICAgZWxzZSB7XG4gICAgICAgICAgICAgICAgICAgIHNlbGYuJFJlZnJlc2hIZWxwZXJzJC5zY2hlZHVsZVVwZGF0ZSgpO1xuICAgICAgICAgICAgICAgIH1cbiAgICAgICAgICAgIH1cbiAgICAgICAgfVxuICAgICAgICBlbHNlIHtcbiAgICAgICAgICAgIC8vIFNpbmNlIHdlIGp1c3QgZXhlY3V0ZWQgdGhlIGNvZGUgZm9yIHRoZSBtb2R1bGUsIGl0J3MgcG9zc2libGUgdGhhdCB0aGVcbiAgICAgICAgICAgIC8vIG5ldyBleHBvcnRzIG1hZGUgaXQgaW5lbGlnaWJsZSBmb3IgYmVpbmcgYSBib3VuZGFyeS5cbiAgICAgICAgICAgIC8vIFdlIG9ubHkgY2FyZSBhYm91dCB0aGUgY2FzZSB3aGVuIHdlIHdlcmUgX3ByZXZpb3VzbHlfIGEgYm91bmRhcnksXG4gICAgICAgICAgICAvLyBiZWNhdXNlIHdlIGFscmVhZHkgYWNjZXB0ZWQgdGhpcyB1cGRhdGUgKGFjY2lkZW50YWwgc2lkZSBlZmZlY3QpLlxuICAgICAgICAgICAgdmFyIGlzTm9Mb25nZXJBQm91bmRhcnkgPSBwcmV2RXhwb3J0cyAhPT0gbnVsbDtcbiAgICAgICAgICAgIGlmIChpc05vTG9uZ2VyQUJvdW5kYXJ5KSB7XG4gICAgICAgICAgICAgICAgbW9kdWxlLmhvdC5pbnZhbGlkYXRlKCk7XG4gICAgICAgICAgICB9XG4gICAgICAgIH1cbiAgICB9XG4iXSwibmFtZXMiOlsiY29uc29sZSIsImxvZyIsIl9hIiwiX2IiLCJzZWxmIiwiY3VycmVudEV4cG9ydHMiLCJtb2R1bGUiLCJfX3Byb3RvX18iLCJleHBvcnRzIiwicHJldkV4cG9ydHMiLCJob3QiLCJkYXRhIiwiJFJlZnJlc2hIZWxwZXJzJCIsInJlZ2lzdGVyRXhwb3J0c0ZvclJlYWN0UmVmcmVzaCIsImlkIiwiaXNSZWFjdFJlZnJlc2hCb3VuZGFyeSIsImRpc3Bvc2UiLCJhY2NlcHQiLCJzaG91bGRJbnZhbGlkYXRlUmVhY3RSZWZyZXNoQm91bmRhcnkiLCJpbnZhbGlkYXRlIiwic2NoZWR1bGVVcGRhdGUiLCJpc05vTG9uZ2VyQUJvdW5kYXJ5Il0sInNvdXJjZVJvb3QiOiIifQ==\\n//# sourceURL=webpack-internal:///./inline.ts\\n\");\n\n/***/ })\n\n/******/ \t});\n/************************************************************************/\n/******/ \t// The module cache\n/******/ \tvar __webpack_module_cache__ = {};\n/******/ \t\n/******/ \t// The require function\n/******/ \tfunction __webpack_require__(moduleId) {\n/******/ \t\t// Check if module is in cache\n/******/ \t\tvar cachedModule = __webpack_module_cache__[moduleId];\n/******/ \t\tif (cachedModule !== undefined) {\n/******/ \t\t\tif (cachedModule.error !== undefined) throw cachedModule.error;\n/******/ \t\t\treturn cachedModule.exports;\n/******/ \t\t}\n/******/ \t\t// Create a new module (and put it into the cache)\n/******/ \t\tvar module = __webpack_module_cache__[moduleId] = {\n/******/ \t\t\tid: moduleId,\n/******/ \t\t\tloaded: false,\n/******/ \t\t\texports: {}\n/******/ \t\t};\n/******/ \t\n/******/ \t\t// Execute the module function\n/******/ \t\tvar threw = true;\n/******/ \t\ttry {\n/******/ \t\t\t__webpack_modules__[moduleId](module, module.exports, __webpack_require__);\n/******/ \t\t\tthrew = false;\n/******/ \t\t} finally {\n/******/ \t\t\tif(threw) delete __webpack_module_cache__[moduleId];\n/******/ \t\t}\n/******/ \t\n/******/ \t\t// Flag the module as loaded\n/******/ \t\tmodule.loaded = true;\n/******/ \t\n/******/ \t\t// Return the exports of the module\n/******/ \t\treturn module.exports;\n/******/ \t}\n/******/ \t\n/************************************************************************/\n/******/ \t/* webpack/runtime/harmony module decorator */\n/******/ \t!function() {\n/******/ \t\t__webpack_require__.hmd = function(module) {\n/******/ \t\t\tmodule = Object.create(module);\n/******/ \t\t\tif (!module.children) module.children = [];\n/******/ \t\t\tObject.defineProperty(module, 'exports', {\n/******/ \t\t\t\tenumerable: true,\n/******/ \t\t\t\tset: function() {\n/******/ \t\t\t\t\tthrow new Error('ES Modules may not assign module.exports or exports.*, Use ESM export syntax, instead: ' + module.id);\n/******/ \t\t\t\t}\n/******/ \t\t\t});\n/******/ \t\t\treturn module;\n/******/ \t\t};\n/******/ \t}();\n/******/ \t\n/******/ \t/* webpack/runtime/make namespace object */\n/******/ \t!function() {\n/******/ \t\t// define __esModule on exports\n/******/ \t\t__webpack_require__.r = function(exports) {\n/******/ \t\t\tif(typeof Symbol !== 'undefined' && Symbol.toStringTag) {\n/******/ \t\t\t\tObject.defineProperty(exports, Symbol.toStringTag, { value: 'Module' });\n/******/ \t\t\t}\n/******/ \t\t\tObject.defineProperty(exports, '__esModule', { value: true });\n/******/ \t\t};\n/******/ \t}();\n/******/ \t\n/******/ \t/* webpack/runtime/react refresh */\n/******/ \t!function() {\n/******/ \t\tif (__webpack_require__.i) {\n/******/ \t\t__webpack_require__.i.push(function(options) {\n/******/ \t\t\tvar originalFactory = options.factory;\n/******/ \t\t\toptions.factory = function(moduleObject, moduleExports, webpackRequire) {\n/******/ \t\t\t\tvar hasRefresh = typeof self !== \"undefined\" && !!self.$RefreshInterceptModuleExecution$;\n/******/ \t\t\t\tvar cleanup = hasRefresh ? self.$RefreshInterceptModuleExecution$(moduleObject.id) : function() {};\n/******/ \t\t\t\ttry {\n/******/ \t\t\t\t\toriginalFactory.call(this, moduleObject, moduleExports, webpackRequire);\n/******/ \t\t\t\t} finally {\n/******/ \t\t\t\t\tcleanup();\n/******/ \t\t\t\t}\n/******/ \t\t\t}\n/******/ \t\t})\n/******/ \t\t}\n/******/ \t}();\n/******/ \t\n/******/ \t/* webpack/runtime/compat */\n/******/ \t\n/******/ \t\n/******/ \t// noop fns to prevent runtime errors during initialization\n/******/ \tif (typeof self !== \"undefined\") {\n/******/ \t\tself.$RefreshReg$ = function () {};\n/******/ \t\tself.$RefreshSig$ = function () {\n/******/ \t\t\treturn function (type) {\n/******/ \t\t\t\treturn type;\n/******/ \t\t\t};\n/******/ \t\t};\n/******/ \t}\n/******/ \t\n/************************************************************************/\n/******/ \t\n/******/ \t// startup\n/******/ \t// Load entry module and return exports\n/******/ \t// This entry module is referenced by other modules so it can't be inlined\n/******/ \tvar __webpack_exports__ = __webpack_require__(\"./inline.ts\");\n/******/ \t\n/******/ })()\n;");
console.log("InlineScript", InlineScript);
var Home = function() {
    return(/*#__PURE__*/ _jsxs("div", {
        className: styles.container,
        __source: {
            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
            lineNumber: 12,
            columnNumber: 5
        },
        __self: _this,
        children: [
            /*#__PURE__*/ _jsxs(Head, {
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 13,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsx("title", {
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 14,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: "Create Next App"
                    }),
                    /*#__PURE__*/ _jsx("meta", {
                        name: "description",
                        content: "Generated by create next app",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 15,
                            columnNumber: 9
                        },
                        __self: _this
                    }),
                    /*#__PURE__*/ _jsx("link", {
                        rel: "icon",
                        href: "/favicon.ico",
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 16,
                            columnNumber: 9
                        },
                        __self: _this
                    })
                ]
            }),
            /*#__PURE__*/ _jsxs("main", {
                className: styles.main,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 19,
                    columnNumber: 7
                },
                __self: _this,
                children: [
                    /*#__PURE__*/ _jsxs("h1", {
                        className: styles.title,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 20,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Welcome to ",
                            /*#__PURE__*/ _jsx("a", {
                                href: "https://nextjs.org",
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 21,
                                    columnNumber: 22
                                },
                                __self: _this,
                                children: "Next.js!"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("p", {
                        className: styles.description,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 24,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            "Get started by editing ",
                            /*#__PURE__*/ _jsx("code", {
                                className: styles.code,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 25,
                                    columnNumber: 34
                                },
                                __self: _this,
                                children: "pages/index.tsx"
                            })
                        ]
                    }),
                    /*#__PURE__*/ _jsxs("div", {
                        className: styles.grid,
                        __source: {
                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                            lineNumber: 28,
                            columnNumber: 9
                        },
                        __self: _this,
                        children: [
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/docs",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 29,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 30,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Documentation →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 31,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Find in-depth information about Next.js features and API."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://nextjs.org/learn",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 34,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 35,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 36,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Learn about Next.js in an interactive course with quizzes!"
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://github.com/vercel/next.js/tree/master/examples",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 39,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 40,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Examples →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 41,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Discover and deploy boilerplate example Next.js projects."
                                    })
                                ]
                            }),
                            /*#__PURE__*/ _jsxs("a", {
                                href: "https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                                className: styles.card,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 44,
                                    columnNumber: 11
                                },
                                __self: _this,
                                children: [
                                    /*#__PURE__*/ _jsx("h2", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 48,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Deploy →"
                                    }),
                                    /*#__PURE__*/ _jsx("p", {
                                        __source: {
                                            fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                            lineNumber: 49,
                                            columnNumber: 13
                                        },
                                        __self: _this,
                                        children: "Instantly deploy your Next.js site to a public URL with Vercel."
                                    })
                                ]
                            })
                        ]
                    })
                ]
            }),
            /*#__PURE__*/ _jsx("footer", {
                className: styles.footer,
                __source: {
                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                    lineNumber: 54,
                    columnNumber: 7
                },
                __self: _this,
                children: /*#__PURE__*/ _jsxs("a", {
                    href: "https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app",
                    target: "_blank",
                    rel: "noopener noreferrer",
                    __source: {
                        fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                        lineNumber: 55,
                        columnNumber: 9
                    },
                    __self: _this,
                    children: [
                        "Powered by",
                        " ",
                        /*#__PURE__*/ _jsx("span", {
                            className: styles.logo,
                            __source: {
                                fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                lineNumber: 61,
                                columnNumber: 11
                            },
                            __self: _this,
                            children: /*#__PURE__*/ _jsx(Image, {
                                src: "/vercel.svg",
                                alt: "Vercel Logo",
                                width: 72,
                                height: 16,
                                __source: {
                                    fileName: "/Users/luke/Projects/create-script/app/pages/index.tsx",
                                    lineNumber: 62,
                                    columnNumber: 13
                                },
                                __self: _this
                            })
                        })
                    ]
                })
            })
        ]
    }));
};
_c = Home;
export default Home;
var _c;
$RefreshReg$(_c, "Home");


;
    var _a, _b;
    // Legacy CSS implementations will `eval` browser code in a Node.js context
    // to extract CSS. For backwards compatibility, we need to check we're in a
    // browser context before continuing.
    if (typeof self !== 'undefined' &&
        // AMP / No-JS mode does not inject these helpers:
        '$RefreshHelpers$' in self) {
        var currentExports = module.__proto__.exports;
        var prevExports = (_b = (_a = module.hot.data) === null || _a === void 0 ? void 0 : _a.prevExports) !== null && _b !== void 0 ? _b : null;
        // This cannot happen in MainTemplate because the exports mismatch between
        // templating and execution.
        self.$RefreshHelpers$.registerExportsForReactRefresh(currentExports, module.id);
        // A module can be accepted automatically based on its exports, e.g. when
        // it is a Refresh Boundary.
        if (self.$RefreshHelpers$.isReactRefreshBoundary(currentExports)) {
            // Save the previous exports on update so we can compare the boundary
            // signatures.
            module.hot.dispose(function (data) {
                data.prevExports = currentExports;
            });
            // Unconditionally accept an update to this module, we'll check if it's
            // still a Refresh Boundary later.
            module.hot.accept();
            // This field is set when the previous version of this module was a
            // Refresh Boundary, letting us know we need to check for invalidation or
            // enqueue an update.
            if (prevExports !== null) {
                // A boundary can become ineligible if its exports are incompatible
                // with the previous exports.
                //
                // For example, if you add/remove/change exports, we'll want to
                // re-execute the importing modules, and force those components to
                // re-render. Similarly, if you convert a class component to a
                // function, we want to invalidate the boundary.
                if (self.$RefreshHelpers$.shouldInvalidateReactRefreshBoundary(prevExports, currentExports)) {
                    module.hot.invalidate();
                }
                else {
                    self.$RefreshHelpers$.scheduleUpdate();
                }
            }
        }
        else {
            // Since we just executed the code for the module, it's possible that the
            // new exports made it ineligible for being a boundary.
            // We only care about the case when we were _previously_ a boundary,
            // because we already accepted this update (accidental side effect).
            var isNoLongerABoundary = prevExports !== null;
            if (isNoLongerABoundary) {
                module.hot.invalidate();
            }
        }
    }
